In [1]:
import pandas as pd
from pyhanlp import *
import jieba
import numpy as np

df = pd.read_excel('Lawsnote法律黑客松＿判決摘要.xlsx',sheet_name='慰撫金')

# 濾除雜質
for idx, row in df.iterrows():
    for col in df.columns:
        if type(df.iloc[idx][col]) == str:
            value = df.iloc[idx][col]
            value = value.strip()
            value = value.replace('未滿','').replace('不明','').replace('未主張','')
            value = value.replace('目前沒有工作','').replace('目前在監服刑','').replace('在監執行','')
            value = value.replace('無','').replace('目前在監服刑','').replace('在監執行','')
            df.iloc[idx][col] = value 
            
        if col == '年齡':
            if ('nan' in value) or (value == ''): df.iloc[idx][col] = 0
                    
                
                                        
# 留下必要row           
col = [c for c in df.columns if c not in ['法院']]
df = df.drop([0,1])
df = df.reset_index(drop=True)
df = df.dropna(subset=['最後判賠金額'])
df = df[df["犯罪類型"] != 'X']

In [2]:
df.head()

,法院,主文,犯罪類型,職業,產業,階級,學歷,年齡,等級,數額,財產總額,財產種類,原告主張,原告年紀,被告主張,有利原告,有利被告,原告要求金額,最後判賠金額
0,臺灣新北地方法院107年訴字第1661號民事判決,臺灣新北地方法院民事判決107年度訴字第1661號原告0000-000000（真實姓名年籍均...,強制性交,"餐飲及溫泉會館,老闆",住宿及餐飲業,老闆,NaN,NaN,經濟狀況良好,1000000,NaN,NaN,服用藥物昏沈不能抗拒,52,,趁原告服用安眠藥法抗拒\n事後悔意從未道歉\n指稱原告設局引誘被告,NaN,800000,500000
2,臺灣高等法院107年上易字第56號民事判決,臺灣高等法院民事判決107年度上易字第56號上訴人王凱民訴訟代理人王俊傑律師被上訴人A女(0...,強制性交未遂,待業,NaN,NaN,大學肄業,NaN,NaN,52540,NaN,NaN,因酒醉不知不能抗拒,NaN,當日因飲酒過量精神恍惚\n證人之證詞互有矛盾\nDNA未為23種型別比對\n請求之賠償金額過高,被告利用原告酒醉不知不能抗拒,NaN,1300000,900000
3,臺灣新北地方法院107年訴字第727號民事判決,臺灣新北地方法院民事判決107年度訴字第727號原告林明子訴訟代理人蔣宗翰律師張君維被告徐松...,性騷擾,待業,NaN,NaN,國小畢業,NaN,NaN,36000,NaN,"投資:1,不動產:1",被告不滿原告以徒手拍打其臀部，而徒手反推原告\n原告當場倒地，造成原告背部外傷及骨折,NaN,正當防衛，傷害故意\n被告才是受害人,NaN,NaN,700000,50000
4,臺灣臺北地方法院106年醫字第16號民事判決,臺灣臺北地方法院民事判決106年度醫字第16號原告A女（真實姓名、住居所詳卷）訴訟代理人周珊...,性騷擾,醫師,醫療保健業,員工,NaN,NaN,NaN,1914876,NaN,NaN,被告趁原告尋求醫療協助之際，要求發生性行為\n醫療行為不當，致原告腿部神經病變,NaN,術前已盡評估之事\n原告為護士，於術前應已了解風險,趁病人不適且法逃脫醫師治療之依賴\n違反道德,NaN,300000,250000
5,臺灣高等法院臺中分院107年訴易字第78號民事判決,臺灣高等法院臺中分院民事判決107年度訴易字第78號原告A女（代號0000-000000）（...,強制性交,待業,NaN,NaN,專科肄業,NaN,輕度精神障礙\n存款\n領有重大傷病證明卡,0,NaN,NaN,被告明知其為低智商而強制性交,NaN,二人互有情愫\n並未暴力脅迫原告\n經濟能力不佳，不應請求高額求償金,被告明知其為低智商而強制性交,NaN,1000000,400000

# Preprocessing

In [3]:
def education(text):
    if text!= None and type(text) == str:
        try:
            text = text.replace('\n','')
            seg_list = jieba.cut(text)
            seg_list = [s for s in seg_list]

            seg_list_1 = "".join(seg_list[:-1])
            seg_list_2 = seg_list[-1]

            if 'nan' in seg_list_2: return [0,0]
            if seg_list_1 == '': return [seg_list_2]
            return [seg_list_1,seg_list_2]
        except Exception as e:
            return [0,0]
    else: return [0,0]

def study(v):
    level = 0
    if type(v[0]) == str:
        text = v[0]
        if text in ['國小']: level = 0
        elif text in ['初中','國中','國 中']: level =  1
        elif text in ['高中','高職','高工','家商']: level =  2
        elif text in ['大學','空中大學','二專','專科','大專','技術學院']: level =  3
        elif text in ['研究','碩士']: level =  4
        elif text in ['博士']: level =  5
        if len(v)>1:
            if '肄業' in v[1]: return (level-0.5)
            else: return level

    
def extract_age(text):
    if type(text) == str:
        seg_list = jieba.cut(text)
        for s in seg_list:
            if s.isdigit(): return int(s)
    else:
        return text   
    

    
    

# 年齡處理
df['年齡'] = df['年齡'].fillna(0)
df['年齡'] = df['年齡'].apply(extract_age)
age_count = [v for v in df['年齡'] if v > 0]
df['年齡'] = df['年齡'].apply(lambda x : x if x>0 else np.mean(age_count)) # 年齡填充


# 學歷處理  
df['學歷'] = df['學歷'].apply(education)
level_dict = [v[0] for v in df['學歷'] if type(v[0]) == str]
level_dict = ['國小','初中','國中','國 中','高中','高職','高工','大學','空中大學','二專','碩士']           
df['學歷'] = df['學歷'].apply(study)  
study_count = [v for v in df['學歷'] if v > 0]
df['學歷'] = df['學歷'].apply(lambda x : x if x>0 else np.mean(study_count)) # 學歷填充
# df['學歷'] = df['學歷'].apply(lambda x : x if x>0 else 2) # 學歷填充


# 原告年紀處理 
df['原告年紀'] = df['原告年紀'].fillna(0)
hurt_age_count = [int(v) for v in df['原告年紀'] if int(v) > 0]
df['原告年紀'] = df['原告年紀'].apply(lambda x : x if x>0 else np.max(hurt_age_count)) # 原告年紀

# df
df[['職業','產業','階級','學歷','年齡']].tail()

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\user\AppData\Local\Temp\jieba.cache
Loading model cost 0.979 seconds.
Prefix dict has been built succesfully.

         職業               產業   階級        學歷         年齡
221   ,公車司機          公共汽車客運業   員工  1.973451  36.272727
222     ,法師          其他個人服務業   老闆  2.000000  36.272727
223      待業              NaN  NaN  1.973451  18.000000
224  ,戲劇製作人  創作及藝術表演業, 藝文服務業   主管  1.973451  36.272727
225      待業              NaN  NaN  1.973451  36.272727

# 薪情平臺匯出資料_數額引用

In [4]:
# 數額填充
import operator
employee = pd.read_excel('Lawsnote法律黑客松＿判決摘要.xlsx',sheet_name='薪情平臺匯出資料') # 薪情平臺匯出資料

employee.head()  
employee_money ={} # 薪資排行榜
employee_mapping={} 
for idx, row in employee.iterrows():
    employee_money[list(row)[0]] = list(row)[2]    
    if type(list(row)[1]) == str:
        employee_mapping[list(row)[0]] = list(row)[1].split(',')
    

employee_rank = sorted(employee_money.items(), key=operator.itemgetter(1),reverse=True)
employee_rank = [e[0] for e in employee_rank]          

def fill_money(row):
    if row['數額']: return row['數額']
    else:
        return employee_money[row['產業']]

    
    
# df['數額'] = df.apply(fill_money)
df['階級'] = df['階級'].fillna('待業')
df['產業'] = df['產業'].fillna('待業')
# df['財產種類'] = df['財產種類'].fillna('無財產')
df[['職業','產業','階級','學歷','年齡','數額']].head()

           職業      產業  階級        學歷         年齡       數額
0  餐飲及溫泉會館,老闆  住宿及餐飲業  老闆  1.973451  36.272727  1000000
2          待業      待業  待業  2.500000  36.272727    52540
3          待業      待業  待業  1.973451  36.272727    36000
4          醫師   醫療保健業  員工  1.973451  36.272727  1914876
5          待業      待業  待業  2.500000  36.272727        0

# 把犯罪類型、階級、財產種類做one hot encoding

In [5]:
# 刪除不必要的columns
df = df.drop(["法院", "主文", "職業", "產業", "等級", "財產總額"], axis=1)
# 所有\n化為，
df.replace('\n','，', inplace=True, regex=True)

# 刪除犯罪類型為nan的index
Nanlist = df[df["犯罪類型"].isnull().values==True].index.tolist()
df = df.drop(Nanlist)

df.reset_index(drop=True, inplace=True)
df.head()

,犯罪類型,階級,學歷,年齡,數額,財產種類,原告主張,原告年紀,被告主張,有利原告,有利被告,原告要求金額,最後判賠金額
0,強制性交,老闆,1.973451,36.272727,1000000,NaN,服用藥物昏沈不能抗拒,52,,趁原告服用安眠藥法抗拒，事後悔意從未道歉，指稱原告設局引誘被告,NaN,800000,500000
1,強制性交未遂,待業,2.500000,36.272727,52540,NaN,因酒醉不知不能抗拒,52,當日因飲酒過量精神恍惚，證人之證詞互有矛盾，DNA未為23種型別比對，請求之賠償金額過高,被告利用原告酒醉不知不能抗拒,NaN,1300000,900000
2,性騷擾,待業,1.973451,36.272727,36000,"投資:1,不動產:1",被告不滿原告以徒手拍打其臀部，而徒手反推原告，原告當場倒地，造成原告背部外傷及骨折,52,正當防衛，傷害故意，被告才是受害人,NaN,NaN,700000,50000
3,性騷擾,員工,1.973451,36.272727,1914876,NaN,被告趁原告尋求醫療協助之際，要求發生性行為，醫療行為不當，致原告腿部神經病變,52,術前已盡評估之事，原告為護士，於術前應已了解風險,趁病人不適且法逃脫醫師治療之依賴，違反道德,NaN,300000,250000
4,強制性交,待業,2.500000,36.272727,0,NaN,被告明知其為低智商而強制性交,52,二人互有情愫，並未暴力脅迫原告，經濟能力不佳，不應請求高額求償金,被告明知其為低智商而強制性交,NaN,1000000,400000

In [6]:
# df["財產種類"].unique()

In [7]:
#犯罪類型 one hot encoding
crime_df = pd.get_dummies(df["犯罪類型"])
crime_df.head()

   乘機性交  強制性交  強制性交、猥褻  強制性交未遂  性騷擾  猥褻  與未成年人合意性交
0     0     1        0       0    0   0          0
1     0     0        0       1    0   0          0
2     0     0        0       0    1   0          0
3     0     0        0       0    1   0          0
4     0     1        0       0    0   0          0

In [8]:
#階級 one hot encoding
level_df = pd.get_dummies(df["階級"])
level_df.head()

   主管  員工  待業  老闆
0   0   0   0   1
1   0   0   1   0
2   0   0   1   0
3   0   1   0   0
4   0   0   1   0

In [9]:
# 財產種類 one hot encoding
t_investment = 0   # 投資
t_real_estate = 0  # 不動產
t_car = 0          # 汽車
t_house = 0        # 房屋
t_land = 0         # 土地
t_motorcycle = 0   # 機車

investment = []   # 投資
real_estate = []  # 不動產
car = []          # 汽車
house = []        # 房屋
land = []         # 土地
motorcycle = []   # 機車

for index in df["財產種類"]:
    if not pd.isnull(index):
        comma = index.split(",")
        for item in comma:
            temp = item.split(":")
            if temp[1] == "n":        # n設定為5
                temp[1] = 5
            
            if temp[0] == "投資":
                t_investment = temp[1]
            elif temp[0] == "不動產":
                t_real_estate = temp[1]
            elif temp[0] == "汽車":
                t_car = temp[1]
            elif temp[0] == "房屋":
                t_house = temp[1]
            elif temp[0] == "土地":
                t_land = temp[1]
            elif temp[0] == "機車":
                t_motorcycle = temp[1]
        investment.append(t_investment)
        real_estate.append(t_real_estate)
        car.append(t_car)
        house.append(t_house)
        land.append(t_land)
        motorcycle.append(t_motorcycle)
        
        t_investment = 0   # 投資
        t_real_estate = 0  # 不動產
        t_car = 0          # 汽車
        t_house = 0        # 房屋
        t_land = 0         # 土地
        t_motorcycle = 0   # 機車
    else:
        investment.append(0)
        real_estate.append(0)
        car.append(0)
        house.append(0)
        land.append(0)
        motorcycle.append(0)

c = {"投資":investment,
     "不動產":real_estate,
     "汽車":car,
     "房屋":house,
     "土地":land,
     "機車":motorcycle}
belongings = pd.DataFrame(c)
belongings.head()

  投資 不動產 汽車 房屋 土地 機車
0  0   0  0  0  0  0
1  0   0  0  0  0  0
2  1   1  0  0  0  0
3  0   0  0  0  0  0
4  0   0  0  0  0  0

In [10]:
# 刪除columns(犯罪類型、階級、財產種類、原告年紀)
from copy import deepcopy
orig_df = deepcopy(df)
df = df.drop(["犯罪類型", "階級", "財產種類", "原告年紀"], axis=1)
df.head()

,學歷,年齡,數額,原告主張,被告主張,有利原告,有利被告,原告要求金額,最後判賠金額
0,1.973451,36.272727,1000000,服用藥物昏沈不能抗拒,,趁原告服用安眠藥法抗拒，事後悔意從未道歉，指稱原告設局引誘被告,NaN,800000,500000
1,2.500000,36.272727,52540,因酒醉不知不能抗拒,當日因飲酒過量精神恍惚，證人之證詞互有矛盾，DNA未為23種型別比對，請求之賠償金額過高,被告利用原告酒醉不知不能抗拒,NaN,1300000,900000
2,1.973451,36.272727,36000,被告不滿原告以徒手拍打其臀部，而徒手反推原告，原告當場倒地，造成原告背部外傷及骨折,正當防衛，傷害故意，被告才是受害人,NaN,NaN,700000,50000
3,1.973451,36.272727,1914876,被告趁原告尋求醫療協助之際，要求發生性行為，醫療行為不當，致原告腿部神經病變,術前已盡評估之事，原告為護士，於術前應已了解風險,趁病人不適且法逃脫醫師治療之依賴，違反道德,NaN,300000,250000
4,2.500000,36.272727,0,被告明知其為低智商而強制性交,二人互有情愫，並未暴力脅迫原告，經濟能力不佳，不應請求高額求償金,被告明知其為低智商而強制性交,NaN,1000000,400000

In [11]:
df.columns

Index(['學歷', '年齡', '數額', '原告主張', '被告主張', '有利原告', '有利被告', '原告要求金額', '最後判賠金額'], dtype='object')

# Word Embedding

In [12]:
from keras.preprocessing.text import Tokenizer
## 使用Tokenizer對詞組進行編碼
## 當我們建立一個Tokenizer對象後，使用該對象的fit_on_texts()函数，以空格去便是每個詞,
## 可以將輸入的文本中的每個詞編號，編號是根據詞頻的，詞頻越大，編號越小。
max_words = 5000
max_len = 600
tok = Tokenizer(num_words=max_words)  ## 使用的最大詞語數为5000
# tok.fit_on_texts(df_seg.seg_word)
# ## 使用word_index屬性可以看到每個詞對應的編碼
# ## 使用word_counts屬性可以看到每個詞對應的頻數
# for ii,iterm in enumerate(tok.word_index.items()):
#     if ii < 10:
#         print(iterm)
#     else:
#         break
# print("===================")  
# for ii,iterm in enumerate(tok.word_counts.items()):
#     if ii < 10:
#         print(iterm)
#     else:
#         break

Using TensorFlow backend.
D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

# word2vec

# 語料庫前處理

In [13]:
# coding=utf-8
import jieba 
from pyhanlp import *
import re
import os
import gensim
analyer = PerceptronLexicalAnalyzer()
# load stopwords set
stopword_set = set()
with open('stopwords.txt','r', encoding='utf-8') as stopwords:
    for stopword in stopwords:
        stopword_set.add(stopword.strip('\n'))

dff_hack = pd.read_csv('dff_badpeople.csv',encoding = 'utf_8')


fileTrainSeg=[]

col_name_list = ['原告主張','被告主張','有利原告','有利被告','主文']

# 檢視斷詞jieba的結果
def PrintListChinese(list):
    for i in range(len(list)):
        print(list[i])
        
def append_seq(col_name):    
    if col_name != '主文':
        print(col_name)
        for idx in range(len(df[col_name])):
            # 斷詞
    #         words = jieba.cut(df.iloc[idx][col_name],cut_all=False)
            article = df.iloc[idx][col_name]           
#             print(article)
            if type(article) == str:
                punctuation = """！？｡＂＃＄％＆＇（）＊＋－／：；＜＝＞＠［＼］＾＿｀｛｜｝～｟｠｢｣､、〃》「」『』【】〔〕〖〗〘〙〚〛〜〝〞〟〰〾〿–—‘'‛“”„‟…‧﹏"""
                re_punctuation = "[{}] ".format(punctuation)
                article = re.sub(re_punctuation, "", article)
                words = analyer.segment(article)
            else:
                continue
            no_stopword_list = []
            for word in words:
#                 if (word not in stopword_set) and (not word.isdigit()) and (word.isalpha()):
                if (word.isalpha()):
                    no_stopword_list.append(word)   
            fileTrainSeg.append([' '.join(no_stopword_list)]) # 精確模式、同時也是預設模式
            # 因為會跑很久，檢核是否資料有持續在跑   
    elif col_name == '主文':
        print(col_name)
        for idx in range(len(dff_hack[col_name])):
            # 斷詞
    #         words = jieba.cut(df.iloc[idx][col_name],cut_all=False)
            article = dff_hack.iloc[idx][col_name]
            if type(article) == str:
                punctuation = """！？｡＂＃＄％＆＇（）＊＋－／：；＜＝＞＠［＼］＾＿｀｛｜｝～｟｠｢｣､、〃》「」『』【】〔〕〖〗〘〙〚〛〜〝〞〟〰〾〿–—‘'‛“”„‟…‧﹏"""
                re_punctuation = r"[{}] ".format(punctuation)
                article = re.sub(re_punctuation, "", article)
                words = analyer.segment(article)
            else:
                continue
            words = analyer.segment(dff_hack.iloc[idx][col_name])
            no_stopword_list = []
            for word in words:
#                 if (word not in stopword_set) and (not word.isdigit()) and (word.isalpha()):
                if (word.isalpha()):                    
                    no_stopword_list.append(word)   
            fileTrainSeg.append([' '.join(no_stopword_list)]) # 精確模式、同時也是預設模式

D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")

In [14]:
# 若沒有則生成語料檔
if not os.path.exists('corpusSegDone.txt'):        
    for col in col_name_list:
        append_seq(col)
    # 將jieba的斷詞產出存檔
    fileSegWordDonePath ='corpusSegDone.txt'
    with open(fileSegWordDonePath,'wb') as fW:
        for i in range(len(fileTrainSeg)):
            fW.write(fileTrainSeg[i][0].encode('utf-8'))
            fW.write('\n'.encode('utf-8'))
else:
    print('corpusSegDone.txt Already exist!')

corpusSegDone.txt Already exist!

# 語料庫Word2Vec訓練

In [15]:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
from gensim.models import word2vec

if not os.path.exists('corpusWord2Vec.bin'):  
    # 將上述 jieba 斷詞後的 corpusSegDone.txt 轉成向量後存成 corpusWord2Vec.bin 檔：
    sentences = gensim.models.word2vec.LineSentence('corpusSegDone.txt')
    w2vec = gensim.models.Word2Vec(sentences, size=300, min_count=1,max_vocab_size=None)
    w2vec.wv.save_word2vec_format('corpusWord2Vec.bin', binary=True)
    w2vec = w2vec.wv.load_word2vec_format('corpusWord2Vec.bin', binary=True)
    # model[fileTrainSeg[0][0].split()]
    print(len(list(w2vec.vocab)))
else:
    print('corpusWord2Vec.bin Already exist!')

corpusWord2Vec.bin Already exist!

# 製造Word2Vec詞庫

In [16]:
from gensim.models.keyedvectors import KeyedVectors
from gensim.test.utils import datapath
# word_vectors = w2vec.wv.load_word2vec_format('corpusWord2Vec.bin', binary=True)

word_vectors = KeyedVectors.load_word2vec_format("corpusWord2Vec.bin", binary=True)

def make_w2v_embeddings(model, df, embedding_dim):  # 将词转化为词向量
    vocabs = {}  # 词序号
    vocabs_cnt = 0  # 词个数计数器

    vocabs_not_w2v = {}  # 无法用词向量表示的词
    vocabs_not_w2v_cnt = 0  # 无法用词向量表示的词个数计数器

    # 停用词
    # stops = set(open('data/stopwords.txt').read().strip().split('\n'))

    for index, row in df.iterrows():
        # 打印处理进度
        if index != 0 and index % 1000 == 0:
            print(str(index) + " sentences embedded.")

        for col in ['原告主張', '被告主張','有利原告','有利被告']:
            vecs = []  # vecs -> col to numbers representation
            words = row[col]
            try:
                for word in  words:
                    # if word in stops:  # 去停用词
                        # continue
                    if word not in list(model.vocab) and word not in vocabs_not_w2v:  # OOV的词放入不能用词向量表示的字典中，value为1
                        vocabs_not_w2v_cnt += 1
                        vocabs_not_w2v[word] = 1
                    if word not in vocabs:  # 非OOV词，提取出对应的id
                        vocabs_cnt += 1
                        vocabs[word] = vocabs_cnt
                        vecs.append(vocabs_cnt)
                    else:
                        vecs.append(vocabs[word])
                if len(vecs) == 0: vecs = [0] * 10
                df.at[index, col + '_vecs'] = vecs
            except Exception as e:
                df.at[index, col + '_vecs'] = [0] * 10

    embeddings = 1 * np.random.randn(len(vocabs) + 1, embedding_dim)  # 随机初始化一个形状为[全部词个数，词向量维度]的矩阵
    '''
    词1 [a1, a2, a3, ..., a60]
    词2 [b1, b2, b3, ..., b60]
    词3 [c1, c2, c3, ..., c60]
    '''
    embeddings[0] = 0  # 第一行用0填充，因为不存在index为0的词

    for index in vocabs:
        vocab_word = vocabs[index]
        if vocab_word in list(model.vocab):
            embeddings[index] = word_vectors[vocab_word]

    return df, embeddings

EMBEDDING_DIM = 300 # max_seq_length

for col in ['原告主張', '被告主張','有利原告','有利被告']:
    df[col + '_vecs'] = df[col]

df, embeddings = make_w2v_embeddings(word_vectors, df, embedding_dim=EMBEDDING_DIM)

D:\Program\Anaconda3\envs\tensorflow\lib\site-packages\smart_open\smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL

# 將句子Padding做語意向量

In [17]:
import itertools
from keras.preprocessing.sequence import pad_sequences

def split_and_zero_padding(df, max_seq_length):  # 调整tokens长度

    # 训练集矩阵转换成字典
    X = {'1': df['原告主張_vecs'], '2': df['被告主張_vecs'], '3': df['有利原告_vecs'], '4': df['有利被告_vecs']}

    # 调整到规定长度
    for dataset, side in itertools.product([X], ['1', '2','3','4']):
        dataset[side] = pad_sequences(dataset[side], padding='pre', truncating='post', maxlen=max_seq_length)

    return dataset

X_train = split_and_zero_padding(df,228)

hack_seq = np.array(X_train['1'],dtype=np.float) # 原告主張_vecs 輸出 Embedding編碼
hack_seq1 = np.array(X_train['2'],dtype=np.float) # 被告主張_vecs 輸出 Embedding編碼
hack_seq2 = np.array(X_train['3'],dtype=np.float) # 有利原告_vecs 輸出 Embedding編碼
hack_seq3 = np.array(X_train['4'],dtype=np.float) # 有利被告_vecs 輸出 Embedding編碼

In [18]:
print(hack_seq.shape)
print(hack_seq1.shape)
print(hack_seq2.shape)
print(hack_seq3.shape)

(210, 228)
(210, 228)
(210, 228)
(210, 228)

In [19]:
hack_seq[0].shape

(228,)

# 刪除不必要的columns，concat所有dataframe，並分割資料

In [20]:
label = df["最後判賠金額"]
# 刪除columns(原告主張, 被告主張, 有利原告, 有利被告, 原告要求金額, 最後判賠金額)
df = df.drop(["原告主張", "被告主張", "有利原告", "有利被告", "原告要求金額", "最後判賠金額"], axis=1)

In [21]:
# final_df = pd.concat([df,crime_df,level_df,belongings,hack_seq_mat,hack_seq_mat1,hack_seq_mat2,hack_seq_mat3],axis=1)
final_df = pd.concat([df,crime_df,level_df,belongings],axis=1)

In [38]:
final_df.head()

,學歷,年齡,數額,原告主張_vecs,被告主張_vecs,有利原告_vecs,有利被告_vecs,乘機性交,強制性交,強制性交、猥褻,...,主管,員工,待業,老闆,投資,不動產,汽車,房屋,土地,機車
0,1.973451,36.272727,1000000,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[11, 12, 13, 1, 2, 14, 15, 3, 16, 9, 10, 17, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,2.500000,36.272727,52540,"[33, 34, 35, 7, 36, 7, 8, 9, 10]","[37, 38, 33, 39, 34, 40, 41, 42, 43, 44, 45, 1...","[32, 13, 72, 2, 12, 13, 34, 35, 7, 36, 7, 8, 9...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1.973451,36.272727,36000,"[32, 13, 7, 73, 12, 13, 74, 75, 76, 77, 78, 79...","[96, 37, 97, 98, 17, 92, 99, 100, 21, 17, 32, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,...,0,0,1,0,1,1,0,0,0,0
3,1.973451,36.272727,1914876,"[32, 13, 11, 12, 13, 104, 66, 105, 106, 107, 1...","[120, 121, 122, 123, 124, 125, 48, 18, 17, 12,...","[11, 118, 47, 7, 134, 135, 16, 136, 137, 105, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,2.500000,36.272727,0,"[32, 13, 144, 36, 79, 57, 145, 146, 147, 82, 1...","[151, 47, 50, 51, 152, 153, 17, 154, 23, 155, ...","[32, 13, 144, 36, 79, 57, 145, 146, 147, 82, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,0,...,0,0,1,0,0,0,0,0,0,0

In [23]:
final_data = np.array(final_df)
label = np.array(label, dtype='float64')

In [24]:
from sklearn.model_selection import train_test_split

train_X,test_X,train_y,test_y =train_test_split(final_data,label, test_size=0.10, random_state=0)

In [25]:
from sklearn.preprocessing import MinMaxScaler
import csv
from sklearn import preprocessing

#資料正規化
def normalize(data):
#     newdf= train_Aug.copy()
    min_max_scaler = preprocessing.MinMaxScaler()                 
    return min_max_scaler.fit_transform(data.reshape(-1,1))

#資料正規化還原
def denormalize(data, norm_value):
    original_value = data.reshape(-1,1)
    norm_value = norm_value.reshape(-1,1)
    
    min_max_scaler = preprocessing.MinMaxScaler()
    min_max_scaler.fit_transform(original_value)
    denorm_value = min_max_scaler.inverse_transform(norm_value)        
    return denorm_value

train_y = normalize(train_y)

# LSTM 特徵

In [26]:
# num_cols = list(final_df.columns[:20])  # num_cols

num_cols = ['學歷', '年齡', '數額','投資', '不動產', '汽車', '房屋', '土地', '機車']
num_df = final_df[num_cols]
# num_df = num_df.drop(['強制性交','猥褻','強制性交未遂','性騷擾','猥褻','與未成年人合意性交','乘機性交','強制性交、猥褻'], axis=1)
# num_df = num_df.drop(['原告主張_vecs','被告主張_vecs','有利原告_vecs','有利被告_vecs'], axis=1)
num_cols = num_df.columns
num_data = np.array(num_df)
num_df.head()

         學歷         年齡       數額 投資 不動產 汽車 房屋 土地 機車
0  1.973451  36.272727  1000000  0   0  0  0  0  0
1  2.500000  36.272727    52540  0   0  0  0  0  0
2  1.973451  36.272727    36000  1   1  0  0  0  0
3  1.973451  36.272727  1914876  0   0  0  0  0  0
4  2.500000  36.272727        0  0   0  0  0  0  0

In [27]:
from sklearn.preprocessing import LabelEncoder
cat_cols = ['主管','員工', '待業', '老闆','乘機性交', '強制性交', '強制性交、猥褻', '強制性交未遂', '性騷擾', '猥褻', '與未成年人合意性交']
cat_df = final_df[cat_cols]
cat_data = np.array(cat_df)
cat_df.head()

   主管  員工  待業  老闆  乘機性交  強制性交  強制性交、猥褻  強制性交未遂  性騷擾  猥褻  與未成年人合意性交
0   0   0   0   1     0     1        0       0    0   0          0
1   0   0   1   0     0     0        0       1    0   0          0
2   0   0   1   0     0     0        0       0    1   0          0
3   0   1   0   0     0     0        0       0    1   0          0
4   0   0   1   0     0     1        0       0    0   0          0

In [28]:
hack_seq_mat = pd.DataFrame(hack_seq) # setence_cols
hack_seq_mat1 = pd.DataFrame(hack_seq1)
hack_seq_mat2 = pd.DataFrame(hack_seq2)
hack_seq_mat3 = pd.DataFrame(hack_seq3)

# merge one seq
hack_seq_df = pd.concat([hack_seq_mat,hack_seq_mat1,hack_seq_mat2,hack_seq_mat3],axis=1)
hack_seq_encode_data = np.array(hack_seq_df)
hack_seq_encode_data.shape

# four unique seq
# hack_seq_encode,hack_seq_encode1,hack_seq_encode2,hack_seq_encode3

(210, 912)

In [29]:
from sklearn.model_selection import train_test_split

# data split
train_num_X,test_num_X, \
train_cat_X,test_cat_X, \
train_hack_seq_X, test_hack_seq_X, \
train_hack_seq1_X, test_hack_seq1_X, \
train_hack_seq2_X, test_hack_seq2_X, \
train_hack_seq3_X, test_hack_seq3_X, \
train_y,test_y = train_test_split(num_data,cat_data,hack_seq,hack_seq1,hack_seq2,hack_seq3,label, test_size=0.10, random_state=0)

# train data 
X_tr_numerical = np.array(train_num_X)
# X_tr_cat = np.array(train_cat_X[:,0][:, np.newaxis])
# X_tr_cat1 = np.array(train_cat_X[:,1][:, np.newaxis])

# test data 
X_te_numerical = np.array(test_num_X)
# X_te_cat = np.array(test_cat_X[:,0][:, np.newaxis])
# X_te_cat1 = np.array(test_cat_X[:,1][:, np.newaxis])

# normalize lstm seq
# train_lstm_hack_seq_X = np.reshape(train_hack_seq_X, (10, max_len, 1))
# train_lstm_hack_seq_X = train_lstm_hack_seq_X / float(320)

In [30]:
# train_cat_X = np.array(train_cat_X)
# train_cat_X.shape

# Accuracy Function

In [31]:
from keras import backend as K

def f1(y_true, y_pred):
    def recall(y_true, y_pred):
        """Recall metric.

        Only computes a batch-wise average of recall.

        Computes the recall, a metric for multi-label classification of
        how many relevant items are selected.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

    def precision(y_true, y_pred):
        """Precision metric.

        Only computes a batch-wise average of precision.

        Computes the precision, a metric for multi-label classification of
        how many selected items are relevant.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision
    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

# LSTM 模型

In [34]:
# model3
from keras.models import Model, Sequential
from keras.layers import CuDNNGRU,CuDNNLSTM,Input, Dense, Embedding,Dropout, concatenate, Bidirectional,Flatten,GlobalAveragePooling1D, GlobalMaxPool1D,TimeDistributed,Reshape
from keras.layers import LSTM
import gc

num_cats = len(cat_cols) # number of categorical features 2
n_steps = 100 # number of timesteps in each sample (cat dimension 1)
n_numerical_feats = len(num_cols) # number of numerical features in each sample  13
n_cat_feats = train_cat_X.shape[1] # 11
# -------------------------------------------------------------------------------------
# numerical_input
numerical_input = Input(shape=(n_numerical_feats,), name='numeric_input')
cat_input = Input(shape=(n_cat_feats,), name='cat_input')

# cat_inputs = []
# for i in range(num_cats):
#     cat_inputs.append(Input(shape=(1,), name='cat' + str(i+1) + '_input'))

# cat_merged = concatenate(cat_inputs)
logits = concatenate([numerical_input, cat_input])
out1 = Dense(1, activation='relu', name='compsate_valse')(logits)
# -------------------------------------------------------------------------------------
# seq_merged

## some config values  
embed_size = 300 # how big is each word vector
max_features = 5000 # how many unique words to use (i.e num rows in embedding vector)
max_len = 228 # max number of words in a question to use

# split encode=> model3_3
seq_inputs = []
for i in range(4):
    inp = Input(shape=(max_len,), name='hack_seq_encode_input' + str(i+1))
    seq_inputs.append(inp)

seq_embedded = []
for i in range(4):
#     emb = Embedding(max_features, embed_size)(seq_inputs[i])
    
    emb = Embedding(max_features, embed_size,trainable=False)(seq_inputs[i])

    seq_embedded.append(emb)

seq_lstm = []    
for i in range(4):
    lstm = LSTM(16, activation='relu', kernel_initializer='random_uniform',return_sequences=True)(seq_embedded[i])
    seq_lstm.append(lstm)
    
seq_merged = concatenate(seq_lstm)
# hidden1 = Dense(units = 64, name='Fuck_Error')(seq_merged)

flat = Flatten()(seq_merged)
hidden2 = Dense(units = 16,activation = 'relu')(flat)
hidden2= Dropout(0.5)(hidden2)

out2 = Dense(units = 1,activation = 'relu')(hidden2)
# -------------------------------------------------------------------------------------
# model1 = Model(inputs = [numerical_input] + [cat_input], outputs=out1) # model_1

# model1.compile(loss='mse',
#               optimizer='adam',
#               metrics=[f1]
#               )
# -------------------------------------------------------------------------------------
# model2 = Model(inputs = seq_inputs, outputs=out2) # model_2

# model2.compile(loss='mse',
#               optimizer='sgd',
#               metrics=[f1])
# -------------------------------------------------------------------------------------
merge  = concatenate([hidden2, logits])
out = Dense(1, activation='relu', name='compsate_valse')(merge)
model3 = Model(inputs = [numerical_input] + [cat_input] + seq_inputs, outputs=out) # model3_3

# losses = {
# 	"category_output": "categorical_crossentropy",
# 	"color_output": "categorical_crossentropy",
# }
model3.compile(loss='mse',
              optimizer='sgd',
              metrics=[f1])
# -------------------------------------------------------------------------------------




model3.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
hack_seq_encode_input1 (InputLa (None, 228)          0
__________________________________________________________________________________________________
hack_seq_encode_input2 (InputLa (None, 228)          0
__________________________________________________________________________________________________
hack_seq_encode_input3 (InputLa (None, 228)          0
__________________________________________________________________________________________________
hack_seq_encode_input4 (InputLa (None, 228)          0
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 228, 300)     1500000     hack_seq_encode_input1[0][0]
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, 228, 300)     1500000     hack_seq_encode_input2[0][0]
__________________________________________________________________________________________________
embedding_3 (Embedding)         (None, 228, 300)     1500000     hack_seq_encode_input3[0][0]
__________________________________________________________________________________________________
embedding_4 (Embedding)         (None, 228, 300)     1500000     hack_seq_encode_input4[0][0]
__________________________________________________________________________________________________
lstm_1 (LSTM)                   (None, 228, 16)      20288       embedding_1[0][0]
__________________________________________________________________________________________________
lstm_2 (LSTM)                   (None, 228, 16)      20288       embedding_2[0][0]
__________________________________________________________________________________________________
lstm_3 (LSTM)                   (None, 228, 16)      20288       embedding_3[0][0]
__________________________________________________________________________________________________
lstm_4 (LSTM)                   (None, 228, 16)      20288       embedding_4[0][0]
__________________________________________________________________________________________________
concatenate_4 (Concatenate)     (None, 228, 64)      0           lstm_1[0][0]
                                                                 lstm_2[0][0]
                                                                 lstm_3[0][0]
                                                                 lstm_4[0][0]
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 14592)        0           concatenate_4[0][0]
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 16)           233488      flatten_1[0][0]
__________________________________________________________________________________________________
numeric_input (InputLayer)      (None, 9)            0
__________________________________________________________________________________________________
cat_input (InputLayer)          (None, 11)           0
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 16)           0           dense_1[0][0]
__________________________________________________________________________________________________
concatenate_3 (Concatenate)     (None, 20)           0           numeric_input[0][0]
                                                                 cat_input[0][0]
__________________________________________________________________________________________________
concatenate_5 (Concatenate)     (None, 36)           0           dropout_1[0][0]
                                                                 concatenate_3[0][0]
__________________________________________________________________________________________________
compsate_valse (Dense)          (None, 1)            37          concatenate_5[0][0]
==================================================================================================
Total params: 6,314,677
Trainable params: 314,677
Non-trainable params: 6,000,000
__________________________________________________________________________________________________

In [35]:
train_cat_X.shape

(189, 11)

In [25]:
X_tr_numerical.shape

NameError: name 'X_tr_numerical' is not defined

In [37]:
# fit the model
# model1.fit([X_tr_numerical, train_cat_X], train_y,batch_size=2, epochs=10,verbose = True)

# model2.fit([train_hack_seq_X,train_hack_seq1_X,train_hack_seq2_X,train_hack_seq3_X], train_y, batch_size=2, epochs=10,verbose = True) # model_2

# model3
history = model3.fit([X_tr_numerical,train_cat_X,train_hack_seq_X,train_hack_seq1_X,train_hack_seq2_X,train_hack_seq3_X], train_y, 
                     validation_data=([X_te_numerical,test_cat_X,test_hack_seq_X,test_hack_seq1_X,test_hack_seq2_X,test_hack_seq3_X], test_y),
                     batch_size=5, epochs=10,verbose = True) # model_3


# or you can use input layer names instead
# model.fit({'numeric_input': X_tr_numerical,
#            'cat1_input': X_tr_cat,
#            'cat2_input': X_tr_cat1},
#            train_y)

Train on 189 samples, validate on 21 samples
Epoch 1/10
189/189 [==============================] - 116s 613ms/step - loss: 6194388082138626484103806976.0000 - f1: 0.0463 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 2/10
189/189 [==============================] - 121s 641ms/step - loss: 1188523319859.4709 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 3/10
189/189 [==============================] - 117s 617ms/step - loss: 1188523336460.1904 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 4/10
189/189 [==============================] - 117s 619ms/step - loss: 1188523333512.8042 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 5/10
189/189 [==============================] - 127s 671ms/step - loss: 1188523322449.2700 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 6/10
189/189 [==============================] - 125s 661ms/step - loss: 1188523317713.9470 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 7/10
189/189 [==============================] - 120s 636ms/step - loss: 1188523315698.4551 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 8/10
189/189 [==============================] - 122s 647ms/step - loss: 1188523344955.5979 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 9/10
189/189 [==============================] - 111s 585ms/step - loss: 1188523350460.2751 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00
Epoch 10/10
189/189 [==============================] - 111s 586ms/step - loss: 1188523339797.6719 - f1: 0.0000e+00 - val_loss: 572261900678.0952 - val_f1: 0.0000e+00

In [39]:
# evaluate the model
def calc_error(test_y,Y_pred):
    error = []
    for i in range(len(test_y)):
        error.append(test_y[i] - Y_pred[i])

    #print("Errors: ", error)
    #print(error)
    squaredError = []
    absError = []
    for val in error:
        squaredError.append(val * val)#平方
        absError.append(abs(val))#誤差絕對值

    #print("Square Error: ", squaredError)
    #print("Absolute Value of Error: ", absError)
    print("MSE = ", sum(squaredError) / len(squaredError))#平均平方誤差MSE


    #from math import sqrt
    #print("RMSE = ", sqrt(sum(squaredError) / len(squaredError)))#平均平方根誤差RMSE
    print("MAE = ", sum(absError) / len(absError))#平均絕對誤差MAE
    

# model1
# loss, acc = model1.evaluate([X_te_numerical, test_cat_X], test_y, verbose=0)
# Y_pred = model1.predict([X_te_numerical, test_cat_X])

# model2
# loss, acc = model2.evaluate([test_hack_seq_X,test_hack_seq1_X,test_hack_seq2_X,test_hack_seq3_X], test_y, verbose=0)
# Y_pred = model2.predict([test_hack_seq_X,test_hack_seq1_X,test_hack_seq2_X,test_hack_seq3_X])

# model3
loss, acc = model3.evaluate([X_te_numerical, test_cat_X,test_hack_seq_X,test_hack_seq1_X,test_hack_seq2_X,test_hack_seq3_X], test_y, verbose=0)
Y_pred = model3.predict([X_te_numerical,test_cat_X,test_hack_seq_X,test_hack_seq1_X,test_hack_seq2_X,test_hack_seq3_X])

print('Test loss:', loss)
Y_pred = denormalize(test_y, Y_pred)
calc_error(test_y,Y_pred)

Test loss: 572261859328.0
MSE =  [3.9547614e+11]
MAE =  [514285.72]

In [40]:
# X_te_cat1

In [41]:
# # predict the model
# cat_data_0 = np.array(cat_data[:,0][:, np.newaxis])
# cat_data_1 = np.array(cat_data[:,1][:, np.newaxis])
# Y_pred = model3_3.predict([X_te_numerical, X_te_cat, X_te_cat1,test_hack_seq_X,test_hack_seq1_X,test_hack_seq2_X,test_hack_seq3_X])
# # preds = model3_3.predict([num_data, cat_data_0,cat_data_1, hack_seq_encode,hack_seq_encode1,hack_seq_encode2,hack_seq_encode3])

In [42]:
Y_pred

array([[150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.],
       [150000.]], dtype=float32)